### ISSUE TITLE
Peer feedback from Mehrdad Fazli

### ISSUE THREAD

**Issue by mehrdadfazli** [UVA-Engineering-Decision-Analysis/Shichen-Li-Project#3]
I liked your presentation Shichen and found your project interesting. However, I was unable to find your integrated document (notebook) here and I could not comment on that. The only file that was there was "Refined Initial Proposal" which was edited over a month ago and based on the presentation does not seem to be up to date. I would gladly give you a more detailed review on your project if you put the final proposal here. 
Best of luck to you.

**Comment by boswell950802** [comment]
I uploaded here "Presentation for SYS 6014"
